version: '3.1'
services:
  backend:
    build: backend/
    container_name: openai_api_proxy
    env_file:
      - .env
    restart: always
    volumes:
      - .:/code
    ports:
      - "3501:3501"
